### ISSUE TITLE
Were you able to decrypt the config file ?

### ISSUE THREAD

**Issue by minanagehsalalma** [streetster/zxhnh298n#1]
I was able to do mine using a script i found online for zte zxhn h108n 

But i want to re encrypt it after editing so i turn off unwanted features like telnet and maybe enable ssh ..

**Comment by mkst** [comment]
Unfortunately not, and I no longer have the router. There is a thread on [StackExchange](https://reverseengineering.stackexchange.com/questions/11626/zte-encrypted-backup-config-file/13808#13808) but I'm not sure that anyone has been successful.

**Comment by minanagehsalalma** [comment]
> There is a thread on [StackExchange](https://reverseengineering.stackexchange.com/questions/11626/zte-encrypted-backup-config-file/13808#13808) but I'm not sure that anyone has been successful.

I have checked it before..but it didn't help as they didn't say anything about the script.

**Comment by streetster** [comment]
What brand/ISP is your router? Can you upload a copy of your `config.bin` file?

**Comment by mkst** [comment]
I misread your original message. What you need to do is to recompress the modified configuration file and add the header back in. If you can upload your config.bin somewhere (the original, not decrypted) I can take a look at it...

**Comment by minanagehsalalma** [comment]
@streetster  

the command used for decryption

`decode_zte_config.py config.bin config.bin.xml --key "GrWM2Hz&LTvz&f^5"
`

[config and script.zip](https://github.com/streetster/zxhnh298n/files/4745911/config.and.script.zip)

or you can decrypt it using router pass view tool 

thanks in advance :).

**Comment by minanagehsalalma** [comment]
@streetster keep me updated.

**Comment by mkst** [comment]
I put together a couple of scripts for decoding/encoding: https://github.com/streetster/zte-config-utility.

You'll need Python and pip, and to `pip install pycrypto` to use it. I have absolutely no idea if it works. Let me know how you get on!

**Comment by minanagehsalalma** [comment]
@streetster  thanks mate worked like a charm :) 

thanks a lot  😊😊😊

**Comment by minanagehsalalma** [comment]
@streetster you can answer the question i asked a long [while ago about this](https://reverseengineering.stackexchange.com/questions/21827/how-can-i-encrypt-a-decrypted-zte-zxhn-h108n-v2-5-config-file) only if you want ... and i will happily accept the answer

**Comment by mkst** [comment]
> @streetster you can answer the question i asked a long [while ago about this](https://reverseengineering.stackexchange.com/questions/21827/how-can-i-encrypt-a-decrypted-zte-zxhn-h108n-v2-5-config-file) only if you want ... and i will happily accept the answer

Great - thanks for confirmation 👍 I'll close this issue now too!
